name: TestWorkflow

on:
  workflow_dispatch:
  pull_request:

jobs:
  Test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create file
        shell: PowerShell
        run: |
          New-Item -Path . -Name "testFile.txt" -ItemType "file" -Value "Hello, World!"

      - name: Get retention days
        id: retention
        run: |
          $branch = "${{ github.ref }}"
          if ($branch -eq "refs/heads/second-branch") {
            echo "days=365" >> $Env:GITHUB_OUTPUT
            echo "Artefact retention days set to 365"
          } else {
            echo "days=14" >> $Env:GITHUB_OUTPUT
            echo "Artefact retention days set to 14"
          }

      - name: Upload file
        uses: actions/upload-artifact@v4
        with:
          name: File
          path: testFile.txt
          retention-days: ${{ steps.retention.outputs.days }}
